// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmUWWynbWtk_5m0g1-yYjPB_bWgIEZd8',
    appId: '1:635376474398:web:eaf461adec21c401cf110f',
    messagingSenderId: '635376474398',
    projectId: 'batalhadeseries-856c4',
    authDomain: 'batalhadeseries-856c4.firebaseapp.com',
    storageBucket: 'batalhadeseries-856c4.firebasestorage.app',
    measurementId: 'G-S5M9W9XSL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADzW0PU9-sU95Gk4quLFB4Vhy1111tQwI',
    appId: '1:635376474398:android:1e965d27993db6e9cf110f',
    messagingSenderId: '635376474398',
    projectId: 'batalhadeseries-856c4',
    storageBucket: 'batalhadeseries-856c4.firebasestorage.app',
  );
}
